# Site settings
title: Minorities and Philosophy at UCSB
email: adunn@umail.ucsb.edu
description: > # this means to ignore newlines until "baseurl:"
  Minorities and Philosophy aims to examine and address issues of minority
  participation in academic philosophy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "map-ucsb.github.io" # the base hostname & protocol for your site
timezone: America/Los_Angeles
encoding: utf-8

permalink: /:title

# Build settings
markdown: kramdown
